eureka: 
  instance: 
    prefer-ip-address: true
  client: 
    serviceUrl:
      #defaultZone: http://abs:1qaz2WSX@10.248.50.221:8761/eureka/
      defaultZone: http://username:password@localhost:9090/eureka/
server:
  port: 8813
spring:
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:8810
    enabled: true
  sleuth:
    sampler:
      percentage: 1.0