server:
    port: 8080
security:
  basic:
    enabled: true
  user:
    name: username  # 用户名
    password: password   # 用户密码
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://username:password@10.17.7.76:7306/eureka/